### ISSUE TITLE
The JSON input text box should indicate an error for invalid JSON

### ISSUE THREAD

**Issue by dhwaneetbhatt** [virallalakia/json-formatter#1]
For invalid JSON format, the user should be informed rather than trying to format the invalid JSON text.

Error is reproducible using the following JSON text (invalid because missing comma):

```
{
    "name": "Batman"
    "work": "Detective"
}
```

**Comment by virallalakia** [comment]
Thank you @dhwaneetbhatt, for pointing this issue.

If the input is not proper JSON format, I will add support to show error message as an add-on to current behavior. In such cases, users will be able to view formatted text (with error message) assuming the text is JSON-like data.

**Comment by virallalakia** [comment]
I have added support to show error message and highlight the line number if the input is not proper JSON format. In such cases, users will be able to view formatted text (with error message) assuming the text is JSON-like data.

An error is shown for invalid JSON formats, e.g.:
```javascript
{
    "name": "Batman"
    "work": "Detective"
}
```
```javascript
{
    "name": "Batman",,"work": "Detective"
}
```

I am closing this issue. Please reopen it if you find any errors with the fix.
